### ISSUE TITLE
connexion utilisateur

### ISSUE THREAD

**Issue by ghost** [felizarc/strangers-server#1]
Ajouter un service permettant de vérifier si un utilisateur existe ou non.
J'ai vu que la création d'utilisateur existait, mais pas de connexion donc dis moi si je me trompe.

Vu ce que j'ai compris sur l'API il faut envoyé le login+password à chaque fois :
-  savoir si l'utilisateur existe au moment de lui ajouter un compte ça fait un peu tard

last edit : finalement juste un truc permettant de faire un check si l'utilisateur existe serait cool. J'ai regardé un peu le code ruby du projet, je pense pas que ça prenne des masses de lignes.

**Comment by felizarc** [comment]
Oui, il faut envoyer le login+password à chaque fois (cf. mail). Pourquoi un service permettant de savoir si un utilisateur existe ou pas serait utile ?

**Comment by ghost** [comment]
Question d'étapes : 
- si étape 1, l'utilisateur rentre ses logins
- étape 2 il veut ajouter un compte mail
- étape 3, on lui dit qu'il y a un problème avec l'ajout d'un compte
- étape 4 on lui redemande son login ça pose problème.

Il faut être sur que passé la fenêtre de connexion, l'utilisateur soit existant.

**Comment by felizarc** [comment]
Juste pour être sûr, il te faudrait juste un truc du genre `GET /users/toto` qui renvoie 404 si toto n'existe pas ou 200 s'il existe ?

**Comment by ghost** [comment]
Alors en fait ça dépend. Dans l'absolue, pour la connexion oui, mais faut vérifier si le mdp est bon aussi.

Mais après, j'ai vu que tu avais fait un service pour récupérer les comptes mails appartenant à un utilisateur, et pour ça il faut le user id il me semble. Peux tu me confirmé ? Vu que l'on fait tout en Basic auth je dois certainement avoir pas pigé je pense vu qu'il ya déjà une identification, tu dois pouvoir récupérer le user id coté serveur.

**Comment by gignonje** [comment]
Ouais ce serait nickel ;)

**Comment by ghost** [comment]
Nope : il faut tester le mdp aussi. C'est un test de connexion, pas d’existence d'un utilisateur...
Méthode simple pour pas t'emmerder : passe ce test d’existence utilisateur en service avec authentification.

**Comment by felizarc** [comment]
Ah ok, il est pas clair ton cahier des charges :P. Je fais ça.

**Comment by felizarc** [comment]
Voilà, tu peux maintenant jouer au ping pong :
- si `GET /ping` renvoie 200, c'est bon
- si `GET /ping` renvoie 401, t'as tipiaké
