### ISSUE TITLE
Retour données recherche

### ISSUE THREAD

**Issue by ghost** [felizarc/strangers-server#2]
Juste histoire de d'écrire comment je vois le retour de la recherche niveau structure.

l'objet réponse en lui même :
- compte mail d'où provient le résultat
- expéditeur du mail
- date du mail
- contenu du mail complet
- chaine de caractère commençant de 50 caractères avant le numéro jusqu'à 50 caractères après le numéro --> permet d'avoir un aperçu dans une liste

Et donc plus globalement, la réponse json du serveur serait une liste de ce type d'objet.

**Comment by felizarc** [comment]
Actuellement, ça renvoie la structure JSON suivante :

``` json
{
  "number": "0102030405" ,
  "before": "This is a test\r\nNumber: ",
  "after": "\r\nBLAH!",
  "from": ["noreply@google.com"]
}
```

Je vais rajouter le compte email et la date mais quid de l'email complet ? Ça risque d’alourdir la réponse et je vois pas trop l’intérêt d'afficher le mail complet ?

**Comment by ghost** [comment]
J'avoue que ça risque de faire un peu lourd. C'est parce que niveau cheminement dans l'application, j'avais imaginé : 
- l'utilisateur fait la requête pour le numéro
- une liste de réponse s'affiche sous le formulaire
- il peut cliquer sur un élément de la liste afin de voir le mail complet.

Peut être une requête supplémentaire pour récupérer l'email après effectivement pour pas alourdir les résultats.
Possibilité de faire un service récupérant un email précis ?

Mais après ça peut être assez optionnel pour l'instant.

**Comment by felizarc** [comment]
J'ai ajouté le compte d'où provient le mail ("account") et la date.

Lorsque tu lances une requête sur `/find`, il te renvoie le nombre d'emails cherchés toutes les secondes, je me suis dis que ça pourrait être cool pour afficher une sorte de progression car c'est long de rechercher dans plusieurs milliers d'emails ;).

Voilà un exemple réel utilisant mon compte mail sur uran01 (j'ai juste remplacé les vrais données par des fausses) :

```
$ curl -i -H "Accept: application/json" -X POST -u 'toto:super toto' -d "number=0601020304" http://localhost:4567/find
HTTP/1.1 200 OK
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block
Content-Type: text/html;charset=utf-8
Connection: close
Server: thin 1.4.1 codename Chromeo

{"status"=>"searching", "email_searched"=>0}
{"status"=>"searching", "email_searched"=>0}
{"status"=>"searching", "email_searched"=>1}
{"status"=>"searching", "email_searched"=>3}
{"before"=>"ISI (Informatique et Syst\xE8mes d'Informations)\r\nFili\xE8re MPL (Management de Projets Logiciels)\r\nT\xE9l : ", "number"=>"06.01.02.03.04", "after"=>"", "from"=>["quel.quun@utt.fr"], "date"=>"2013-01-06T16:49:12+01:00", "account"=>"moi@uran01.utt.fr", "status"=>"found", "email_searched"=>3}
```

La dernière ligne retournée contient le résultat de la recherche.

Je déploie tout ça dans 5 min.

**Comment by felizarc** [comment]
Voilà c'est en prod, je vous laisse tester avec votre compte sur uran01 (pas gmail).

**Comment by gignonje** [comment]
Je crois que ca risque d'être difficile pour moi de tester... Avec mon transfert j'ai 0 mails sur l'adresse de l'UTT, et ca me sort ce souci:

curl -i -H "Accept: application/json" -X POST -u 'shadow:shadow' -d "number=0601020304" http://ks389666.kimsufi.com:4567/find
HTTP/1.1 200 OK
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block
Content-Type: text/html;charset=utf-8
Connection: close
Server: thin 1.5.0 codename Knife

{"status"=>"searching", "email_searched"=>0}
WTF: [#<Account @id=2 @user_id=2 @host="uran01.utt.fr" @port=993 @username="gignonje" @password=nil @crypted_password="U2FsdGVkX1/w6Am1z5wsilvBfFKjAMBFF0rBuq00K+E=\n" @folder=nil @description=nil @created_at=#<DateTime: 2013-01-07T00:29:31+01:00 ((2456299j,84571s,0n),+3600s,2299161j)> @updated_at=#<DateTime: 2013-01-07T00:29:31+01:00 ((2456299j,84571s,0n),+3600s,2299161j)>>]

Après, est-ce que c'est une erreur de mon côté niveau config, peut être...

**Comment by felizarc** [comment]
Effectivement, si t'as un .forward et donc zéro mail dans ta boite UTT, ça va être dur de tester. Le problème c'est que GMail n'autorise plus de connexion IMAP sans passer par OAuth et c'est chiant à gérer.
T'as pas un compte mail chez OVH/Gandi/etc. qui pourrait faire l'affaire ?

**Comment by felizarc** [comment]
Finalement, pas besoin d'afficher de progression. La requête est bloquante pendant quelques secondes puis retourne le résultat d'un coup. Par exemple :

``` json
{"before":"bla bla","number":"06.01.02.03.04","after":"bla bla","from":["quel.quun@utt.fr"],"date":"2012-10-05T19:54:12+02:00","account":"toto@titi.fr@mail.gandi.net","status":"found"}
```

Si le numéro n'est pas trouvé, ça renvoie juste :

``` json
{"status":"not_found"}
```

/cc @Xquicky @jeremygignon

**Comment by ghost** [comment]
@felizarc Et si tu as plusieurs réponses, ça se présente sous quelle forme ?

**Comment by felizarc** [comment]
Pour l'instant, ça renvoie que la première.
