### ISSUE TITLE
Erreur lors de l'ajout de comptes mails

### ISSUE THREAD

**Issue by gignonje** [felizarc/strangers-server#4]
La création de comptes mails produit une exception, pourtant il apparaît que l'authentification doit être bonne, et les paramètres au bon format. 
Je te joins une copie d'écran du retour si tu en as besoin pour débug ;)

![DataMapper::SaveFailureError 2013-01-05 17-56-13](https://f.cloud.github.com/assets/1492645/45224/ef42ace2-5758-11e2-958f-1dccd1f8bc33.png)

**Comment by felizarc** [comment]
J'avais pas accès à la dernière version quand j'ai déployé ça donc c'était une vieille version buguée qui tournait :). Je viens de déployer la dernière version, tu peux ressayer et me dire si ça marche maintenant ?

**Comment by gignonje** [comment]
Erreur 500 :\

curl -i -H "Accept: application/json" -X POST -u 'shadow:shadow' -d "account[host]=imap.googlemail.com&account[username]=shadowemail&account[password]=shadowemail" http://ks389666.kimsufi.com:4567/accounts/new
HTTP/1.1 500 Internal Server Error
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block
Content-Type: text/html;charset=utf-8
Content-Length: 30
Connection: keep-alive
Server: thin 1.5.0 codename Knife

<h1>Internal Server Error</h1>

**Comment by felizarc** [comment]
Le problème se produisait lorsque l'utilisateur n'existait pas, c'est corrigé.

**Comment by gignonje** [comment]
Euh... Je suis pas d'accord, je suis certain de mon couple user/password : /

**Comment by felizarc** [comment]
J'ai reset la BDD, t'as recréé ton compte ?

**Comment by gignonje** [comment]
Ouais, le compte est recrée, je le vérifie directement au niveau sqlite, c'est bien ca: "-X POST -u 'shadow:shadow'" pour l'auth?
