### ISSUE TITLE
connexion utilisateur (comme je ne peux réouvrir)

### ISSUE THREAD

**Issue by ghost** [felizarc/strangers-server#6]
Il faut tester le mdp aussi. C'est un test de connexion, pas d’existence d'un utilisateur...
Méthode simple pour pas t'emmerder : passe ce test d’existence utilisateur en service avec authentification.

ps : sur github c'est étrange, le créateur de l'issue ne peux pas la réouvrir si le propriétaire du projet la ferme...

**Comment by felizarc** [comment]
Bizarre que tu puisses pas ré-ouvrir l'issue en effet.

Sinon c'est fait, cf. #1.
