### ISSUE TITLE
Erreur recherche de numéro

### ISSUE THREAD

**Issue by ghost** [felizarc/strangers-server#7]
J'ai cette erreur quand je recherche le numéro de lermercier (0325715846) : 

<h1>Internal Server Error</h1>

Si tu pouvais checker en curl avec mon compte (xavier, x).

j'ai essayé avec mon compte uran01.utt.fr port 995 et avec mon compte imap gmail imap.gmail.com

**Comment by felizarc** [comment]
Port 995 ? C'est 993 normalement, tu peux re-tester ?
