### ISSUE TITLE
Suppression utilisateur

### ISSUE THREAD

**Issue by ghost** [felizarc/strangers-server#8]
Après avoir supprimé un utilisateur avec le service delete, il doit rester des traces de ce dernier car il est impossible de recréer un compte directement avec le même login.

**Comment by gignonje** [comment]
Je plussoie, ca ne fonctionne plus, mais ca fonctionnait parfaitement avant... :\
En vérifiant au niveau DB, l'utilisateur est toujours présent. 
Peut être une erreur à la suppression dûe au fait que des comptes mails existent ?
